import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const mediaRoot=path.resolve(process.env.MEDIA_ROOT||process.env.PHOTO_ROOT||root);
const phoneMode=Boolean(process.env.MEDIA_ROOT||process.env.PHOTO_ROOT);
const extensions=new Set(['.mp3']);
let tracks=new Map(),sourceFolders=[],destinationFolders=new Map();
const staticFiles=new Map([['/',['index.html','text/html; charset=utf-8']],['/index.html',['index.html','text/html; charset=utf-8']],['/style.css',['style.css','text/css; charset=utf-8']],['/app.js',['app.js','text/javascript; charset=utf-8']]]);

function isInside(base,file){const r=path.relative(base,file);return r&&r!=='..'&&!r.startsWith('..'+path.sep)&&!path.isAbsolute(r)}
function insideMediaRoot(file){return isInside(mediaRoot,file)}
function publicTrack(file){const relative=path.relative(mediaRoot,file);return{id:Buffer.from(relative).toString('base64url'),name:path.basename(file),location:relative}}
async function resolveFolder(id){const relative=Buffer.from(String(id||''),'base64url').toString(),directory=path.resolve(mediaRoot,relative);if(directory!==mediaRoot&&!insideMediaRoot(directory))throw Error('Invalid folder');const info=await fs.lstat(directory);if(!info.isDirectory()||info.isSymbolicLink())throw Error('Invalid folder');return{relative:relative||'.',directory}}
function musicRoot(){return path.join(mediaRoot,'Music')}
async function createDestinationFolder(name){const clean=String(name||'').trim().replace(/[\\/:*?"<>|]/g,'').replace(/\s+/g,' ');if(!clean||clean==='.'||clean==='..')throw Error('Invalid folder name');if(clean.length>80)throw Error('Folder name is too long');const base=musicRoot();await fs.mkdir(base,{recursive:true});const directory=path.join(base,clean);if(path.dirname(directory)!==base)throw Error('Invalid folder name');try{await fs.mkdir(directory)}catch(e){if(e.code!=='EEXIST')throw e}const info=await fs.lstat(directory);if(!info.isDirectory()||info.isSymbolicLink())throw Error('Folder name is not available');const relative=path.relative(mediaRoot,directory);return{id:Buffer.from(relative).toString('base64url'),name:clean,location:relative}}
async function scanDestinationFolders(){const base=musicRoot();let entries;try{entries=await fs.readdir(base,{withFileTypes:true})}catch(e){if(e.code==='ENOENT'){await fs.mkdir(base,{recursive:true});return[]}if(['EACCES','EPERM'].includes(e.code))throw Error('Termux cannot read the Music folder');throw e}return entries.filter(e=>e.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true})).map(e=>{const relative=path.relative(mediaRoot,path.join(base,e.name));return{id:Buffer.from(relative).toString('base64url'),name:e.name,location:relative}})}
async function scanSourceFolders(){const results=[],pending=[mediaRoot];while(pending.length){const directory=pending.pop();let entries;try{entries=await fs.readdir(directory,{withFileTypes:true})}catch(e){if(['EACCES','EPERM','ENOENT'].includes(e.code))continue;throw e}let mp3Count=0;for(const entry of entries){const file=path.join(directory,entry.name);if(file!==mediaRoot&&!insideMediaRoot(file))continue;if(entry.isDirectory()){if(!['.git','node_modules'].includes(entry.name))pending.push(file)}else if(entry.isFile()&&extensions.has(path.extname(entry.name).toLowerCase()))mp3Count++}if(mp3Count){const relative=path.relative(mediaRoot,directory)||'.';results.push({id:Buffer.from(relative).toString('base64url'),name:path.basename(directory)||path.basename(mediaRoot),location:relative,mp3Count})}}results.sort((a,b)=>a.location.localeCompare(b.location,undefined,{numeric:true}));sourceFolders=results;return results}
async function selectSourceFolder(id){const {relative,directory}=await resolveFolder(id),entries=await fs.readdir(directory,{withFileTypes:true});const found=entries.filter(e=>e.isFile()&&extensions.has(path.extname(e.name).toLowerCase())).map(e=>path.join(directory,e.name)).sort((a,b)=>path.basename(a).localeCompare(path.basename(b),undefined,{numeric:true}));tracks=new Map(found.map(file=>[publicTrack(file).id,file]));return{folder:relative,tracks:[...tracks.values()].map(publicTrack)}}
async function setDestination(slot,id){const n=Number(slot);if(!Number.isInteger(n)||n<1||n>8)throw Error('Destination slot must be 1 through 8');const resolved=await resolveFolder(id),base=musicRoot();if(resolved.directory!==base&&!isInside(base,resolved.directory))throw Error('Destination must be inside Music');destinationFolders.set(String(n),resolved);return{slot:String(n),folder:resolved.relative,name:path.basename(resolved.directory)||resolved.relative}}
async function sortTrack(id,slot){if(typeof id!=='string'||!tracks.has(id))return{error:'MP3 is no longer in the queue',status:404};if(!/^[1-8]$/.test(String(slot)))return{error:'Choose destination slot 1 through 8',status:400};const source=tracks.get(id),chosen=destinationFolders.get(String(slot));if(!chosen)return{error:'Assign destination slot '+slot+' first',status:400};const info=await fs.lstat(source);if(!info.isFile()||!insideMediaRoot(source))return{error:'Invalid source',status:400};const targetInfo=await fs.lstat(chosen.directory);if(!targetInfo.isDirectory()||chosen.directory!==musicRoot()&&!isInside(musicRoot(),chosen.directory))return{error:'Destination folder is not safe',status:400};const original=path.basename(source),ext=path.extname(original),stem=original.slice(0,-ext.length);let destination;for(let n=0;;n++){destination=path.join(chosen.directory,n?`${stem} (${n})${ext}`:original);try{await fs.stat(destination)}catch(e){if(e.code==='ENOENT')break;throw e}}await fs.rename(source,destination);tracks.delete(id);return{movedTo:path.relative(mediaRoot,destination),remaining:tracks.size}}
function cors(req,res){const origin=req.headers.origin||'';if(origin==='https://chunter-gh.github.io'||origin==='http://127.0.0.1:3000'||origin==='http://localhost:3000'){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin')}res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Private-Network','true')}
function json(res,code,value){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>4096)throw Error('Request is too large')}return JSON.parse(raw||'{}')}
const server=http.createServer(async(req,res)=>{try{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&staticFiles.has(url.pathname)){const[file,type]=staticFiles.get(url.pathname);res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});res.end(await fs.readFile(path.join(root,file)))}else if(req.method==='POST'&&url.pathname==='/api/scan-source-folders')json(res,200,{root:path.basename(mediaRoot),folders:await scanSourceFolders()});else if(req.method==='GET'&&url.pathname==='/api/destination-folders')json(res,200,{root:'Music',folders:await scanDestinationFolders()});else if(req.method==='POST'&&url.pathname==='/api/create-destination-folder'){const{name}=await body(req);json(res,200,await createDestinationFolder(name))}else if(req.method==='POST'&&url.pathname==='/api/select-source-folder'){const{id}=await body(req);json(res,200,await selectSourceFolder(id))}else if(req.method==='POST'&&url.pathname==='/api/set-destination'){const{slot,id}=await body(req);json(res,200,await setDestination(slot,id))}else if(req.method==='POST'&&url.pathname==='/api/sort'){const{id,folder}=await body(req),r=await sortTrack(id,folder);json(res,r.status||200,r)}else json(res,404,{error:'Not found'})}catch(e){console.error(e);json(res,500,{error:e.message||'Unexpected error'})}});
const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||3020);
server.listen(port,host,async()=>{console.log(`MP3 Flip Sorter V1 Termux is ready at http://${host}:${port}`);if(phoneMode)try{const found=await scanSourceFolders();console.log(`V1 found ${found.length} folders containing MP3s under ${mediaRoot}`)}catch(e){console.error('V1 MP3 scan failed:',e.message)}});